### ISSUE TITLE
Couldn't find pycache and venv folder...

### ISSUE THREAD

**Issue by JaechangKo** [simpleSketche/simple-sketches#1]
Hello, I'm trying to find out the pycache and venv folder but couldn't figure out where to find them...
![error](https://user-images.githubusercontent.com/10793897/216794436-9e0162e7-5e5d-4701-a24b-888a32b9bb03.JPG)

**Comment by simpleSketche** [comment]
@JaechangKo `venv` folder is created through python virtual enviornment. Please follow this link for more info: https://docs.python.org/3/library/venv.html
In order to run this project, you need to create the virtual environment, and install all the necessary python modules from requirements.txt into this environment. Finally, run app.py in this environment to initialize the flask server.

**Comment by JaechangKo** [comment]
Yes! It works. It's amazing...!! Thank you!
